"""hosting_repo_wrapped_key

Revision ID: 2cd3d64fe32a
Revises: 3ab7604d418c
Create Date: 2026-07-01 11:49:55.780998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2cd3d64fe32a'
down_revision: Union[str, None] = '3ab7604d418c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_repos', sa.Column('wrapped_data_key', sa.JSON(), nullable=True))
    op.add_column('hosting_accounts', sa.Column('wrapped_data_key', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosting_accounts', 'wrapped_data_key')
    op.drop_column('git_repos', 'wrapped_data_key')
    # ### end Alembic commands ###
